name: repo_tool
description: Repo tooling to help validate dart skills.
version: 1.0.0

environment:
  sdk: ^3.11.6

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  logging: ^1.2.0
  skills_lint:
    git:
      url: https://github.com/google/skills_lint.dart.git
      path: packages/skills_lint
      ref: main
  test: ^1.25.6